driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: freebsd-10.3
    driver:
      ssh:
        shell: '"/bin/sh"'
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: package_install
    run_list:
      - recipe[php::default]
  - name: source_install
    run_list:
      - recipe[php::default]
    attributes: { php: { install_method: "source" } }
  - name: resource_test
    run_list:
      - recipe[php::default]
      - recipe[php_test::default]
